name: tradecus
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.1
  http: ^1.2.1
  url_launcher: ^6.0.12
  cupertino_icons: ^1.0.6
  fluttertoast: ^8.2.4
  flutter_spinkit: ^5.2.1
  flutter_dotenv: ^5.1.0
  flutter_rating_bar: ^4.0.0
  flutter_staggered_grid_view: ^0.4.0
  carousel_slider: ^4.2.1
  video_player: ^2.2.14
  cached_network_image: ^3.2.0
  pay: ^2.0.0
  shared_preferences: ^2.2.3
  provider: ^6.0.3
  intl: ^0.18.0 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/logo.png
    - assets/images/gallery-01.webp
    - assets/images/gallery-02.webp
    - assets/images/gallery-03.webp
    - assets/images/gallery-04.webp
    - assets/images/gallery-05.webp
    - assets/images/gallery-06.webp
    - assets/images/gallery-07.webp
    - assets/images/gallery-08.webp
    - assets/images/teamImg.webp
    - assets/images/male-tourist.png
    - assets/images/hero-video.mp4
    - assets/images/hero-img02.webp
    - assets/images/hero-img01.webp
    - .env
    - assets/images/weather.png
    - assets/images/guide.png
    - assets/images/customization.png

  uses-material-design: true
